/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas.view;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uas.controller.ControllerBarang;
import uas.model.ModelBarang;
import uas.util.Koneksi;

/**
 *
 * @author Toshiba
 */
public class ViewBarang extends javax.swing.JFrame {
    Koneksi koneksi = new Koneksi();
    ControllerBarang cb = new ControllerBarang();
    ModelBarang mb = new ModelBarang();

    /**
     * Creates new form ViewBarang
     */
    public ViewBarang() {
        initComponents();
        setLocationRelativeTo(null);//supaya layout berada di tengah
        dataTable();
        
    }
    
    private void baru() {
        btn_baru.setEnabled(false);
        btn_bersih.setEnabled(true);
        btn_hapus.setEnabled(false);
        btn_tutup.setEnabled(false);
        jtx_jenis.setEditable(true);
        jtx_jumlah.setEditable(true);
        jtx_nama.setEditable(true);
        bersih();
    }
     private void bersih() {
        jtx_id.setText("");
        jtx_jenis.setText("");
        jtx_jumlah.setText("");
        jtx_tampil.requestFocus();
        jtx_nama.requestFocus();
    }
     private void bersih2() {
        btn_baru.setEnabled(true);
        btn_bersih.setEnabled(false);
        btn_hapus.setEnabled(false);
        btn_simpan.setEnabled(false);
        btn_tutup.setEnabled(false);
        btn_ubah.setEnabled(false);
        jtx_nama.setEditable(false);
        jtx_jumlah.setEditable(false);
        jtx_jenis.setEditable(false);
        bersih();
    }
     private void ubahDanHapus() {
        btn_simpan.setEnabled(false);
        jtx_nama.setEditable(true);
        jtx_jumlah.setEditable(true);
        jtx_jenis.setEditable(true);
        btn_hapus.setEnabled(true);
        btn_ubah.setEnabled(true);
    }
   
     private void dataTable() {
        koneksi.koneksiDatabase();

        DefaultTableModel tabel = new DefaultTableModel();

        tabel.addColumn("id barang");
        tabel.addColumn("Nama Barang");
        tabel.addColumn("Jenis Barang");
        tabel.addColumn("Jumlah Barang");

        jtx_tampil.setModel(tabel);
        try {
            String sql = "select * from tbl_barang";

            ResultSet res = koneksi.state.executeQuery(sql);
            while (res.next()) {
                tabel.addRow(new Object[]{
                    res.getString("id barang"),
                    res.getString("Nama Barang"),
                    res.getString("Jenis Barang"),
                    res.getString("Jumlah Barang")
                        
                });
                jtx_tampil.setModel(tabel);

            }
        } catch (SQLException eer) {
            System.err.println("SQLException:" + eer.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_baru = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_bersih = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_tutup = new javax.swing.JButton();
        jtx_id = new javax.swing.JTextField();
        jtx_nama = new javax.swing.JTextField();
        jtx_jenis = new javax.swing.JTextField();
        jtx_jumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtx_tampil = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("id Barang     :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setText("Nama Barang     :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setText("Jenis Barang     :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setText("Jumlah Barang     :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btn_baru.setText("Baru");
        getContentPane().add(btn_baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        btn_bersih.setText("Bersih");
        getContentPane().add(btn_bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        btn_ubah.setText("Ubah");
        getContentPane().add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        btn_hapus.setText("Hapus");
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        btn_tutup.setText("Tutup");
        getContentPane().add(btn_tutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jtx_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx_idActionPerformed(evt);
            }
        });
        getContentPane().add(jtx_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 150, -1));
        getContentPane().add(jtx_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 170, -1));
        getContentPane().add(jtx_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 150, -1));

        jtx_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx_jumlahActionPerformed(evt);
            }
        });
        getContentPane().add(jtx_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 170, -1));

        jtx_tampil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id Barang", "Nama Barang", "Jenis Barang", "Jumlah Barang"
            }
        ));
        jScrollPane1.setViewportView(jtx_tampil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 530, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtx_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_idActionPerformed

    private void jtx_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_jumlahActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btn_bersih;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tutup;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtx_id;
    private javax.swing.JTextField jtx_jenis;
    private javax.swing.JTextField jtx_jumlah;
    private javax.swing.JTextField jtx_nama;
    private javax.swing.JTable jtx_tampil;
    // End of variables declaration//GEN-END:variables
}
